[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build && npm run db:push"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
